@localUrl = http://localhost:7071
@endpoint = api/UrlToPdf
@urlToConvert = https://www.google.com

### No params (Invalid)
GET {{localUrl}}/{{endpoint}}

### Query params
GET {{localUrl}}/{{endpoint}}/?url={{urlToConvert}}

### Params on body
POST {{localUrl}}/{{endpoint}}
Content-Type: application/json

{
  "url": "{{urlToConvert}}"
}

### Remote call
### Prepare this call by adding 'SVRLSSPDF_REMOTE_URL' and 'SVRLSSPDF_API_URLTOPDF_CODE' values to a local .env file
@remoteUrl = {{$processEnv SVRLSSPDF_REMOTE_URL}}{{$dotenv SVRLSSPDF_REMOTE_URL}}
@authenticationCode = {{$processEnv SVRLSSPDF_API_URLTOPDF_CODE}}{{$dotenv SVRLSSPDF_API_URLTOPDF_CODE}}

GET {{remoteUrl}}/{{endpoint}}/?url={{urlToConvert}}&&code={{authenticationCode}}
