name: Deploy CI # Deploy Node.js project to Azure Function App

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_NAME: "serverless-pdf" # Function app name on Azure
  NODE_VERSION: "18.x"
  PACKAGE_JSON_PATH: "src"
  BUILD_PATH: "dist"
  PUBLISH_PROFILE: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install rimraf
        run: sudo apt-get install node-rimraf

      - name: "Build package with Yarn"
        shell: bash
        run: |
          yarn build
        working-directory: ./${{ env.PACKAGE_JSON_PATH }}

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.APP_NAME }}
          app-settings-json: '[{ "name": "WEBSITE_RUN_FROM_PACKAGE", "value": "1" }]'
        id: settings

      - name: "Az CLI logout"
        run: |
          az logout
          az cache purge
          az account clear

      - name: "Zip and deploy to Azure"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.APP_NAME }}
          package: ./${{ env.BUILD_PATH }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          respect-funcignore: true
